### ISSUE TITLE
DockerHub

### ISSUE THREAD

**Issue by berlinfox** [CloudNativeJS/helm#8]
Maybe a stupid question, but what if I only want to deploy on my local machine without using DockerHub?

**Comment by chikamichi** [comment]
You’d have to run a registry locally (could be [docker’s _registry_](https://docs.docker.com/registry/deploying/), [Trow](https://trow.io/), [Harbor](https://goharbor.io/), etc.), and make sure to build _and tag_ your image accordingly:

- for _registry_ (docker’s default registry implementation) => just omit the registry name ie. `docker build -t myimage:0.1.0`
  - in the absence of a prefix, `docker run` etc. will first try to find the image locally, then on Docker Hub
- for other registries (eg. Trow, Harbor, etc.) => explicitly set that registry’s IP as a prefix ie. `docker build -t localhost:5000/myimage:0.1.0` or `docker build -t myregistry.mydomain.tld/myimage:0.1.0`, etc.

**Comment by berlinfox** [comment]
Thank you. That really helps!
